'use client';

import type { GenerateCodeOutput } from '@/ai/flows/generate-code-from-description';
import { AIGenerator } from '@/components/dashboard/ai-generator';
import { CodeEditor } from '@/components/dashboard/code-editor';
import { FileManager } from '@/components/dashboard/file-manager';
import { Header } from '@/components/dashboard/header';
import { PreviewPanel } from '@/components/dashboard/preview-panel';
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from '@/components/ui/resizable';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useI18n } from '@/lib/i18n';
import { CodeXml, FolderKanban, Monitor } from 'lucide-react';
import { useState } from 'react';

export default function Home() {
  const [generatedCode, setGeneratedCode] = useState<GenerateCodeOutput>({
    generatedCode: `// The code generated by the AI will appear here.`,
    language: 'typescript',
  });
  const { t } = useI18n();

  return (
    <div className="flex h-screen flex-col font-body bg-background text-foreground">
      <Header />
      <div className="flex-1 flex border-t border-border overflow-hidden">
        <ResizablePanelGroup direction="horizontal">
          <ResizablePanel defaultSize={50} minSize={30}>
            <AIGenerator onCodeGenerated={setGeneratedCode} />
          </ResizablePanel>
          <ResizableHandle withHandle />
          <ResizablePanel defaultSize={50} minSize={30}>
            <Tabs defaultValue="file-manager" className="h-full flex flex-col">
              <div className="border-b">
                <TabsList className="p-0 m-2 rounded-md">
                    <TabsTrigger value="file-manager" className="h-8 gap-2 text-sm">
                      <FolderKanban className="h-4 w-4" />
                      {t('file.manager.title')}
                    </TabsTrigger>
                    <TabsTrigger value="code-editor" className="h-8 gap-2 text-sm">
                      <CodeXml className="h-4 w-4" />
                      {t('code.editor.title')}
                    </TabsTrigger>
                    <TabsTrigger value="preview" className="h-8 gap-2 text-sm">
                      <Monitor className="h-4 w-4" />
                      {t('preview.panel.title')}
                    </TabsTrigger>
                </TabsList>
              </div>
              <TabsContent value="file-manager" className="flex-1 overflow-y-auto mt-0">
                <FileManager />
              </TabsContent>
              <TabsContent value="code-editor" className="flex-1 overflow-y-auto mt-0">
                <CodeEditor
                  code={generatedCode.generatedCode}
                  language={generatedCode.language}
                />
              </TabsContent>
              <TabsContent value="preview" className="flex-1 overflow-y-auto mt-0">
                <PreviewPanel />
              </TabsContent>
            </Tabs>
          </ResizablePanel>
        </ResizablePanelGroup>
      </div>
    </div>
  );
}
